Config env var startup
Tech-Workers-Coalition-Italia/mobilizon-reshare pull request #124
Opened 2022-01-04 17:57 UTC by magowiz

2022-01-04 20:32 UTC, chobeat commented on tests/conftest.py
> +        if not os.environ.get(key):
i test devono essere deterministici quindi questa condizione secondo me crea più problemi che altro. Se un utente specifica per sbaglio dell envvar che vanno in conflitto coi test, è un motivo ulteriore per sovrascriverle.

2022-01-04 23:55 UTC, magowiz commented
OK quindi se rimuovo l'if e imposto comunque quella variabile al valore del dizionario dovrebbe essere più in linea con quel che si vuole ottenere? In tal modo la variabile d'ambiente esisterà sempre e avrà sempre quel valore durante i test. Se ho ben inteso, procederei applicando la modifica. Appena mi confermi faccio un nuovo commit.

2022-01-06 13:34 UTC, magowiz commented
fatto nuovo commit senza l'if, tutte le variabili nel dizionario vengono impostate al relativo valore, a prescindere se siano o meno già definite.

2022-01-08 00:07 UTC, fishinthecalculator requested changes
Secondo me puo' essere un buon workaround fino a che non troviamo qualcosa di meglio, pero':

- andrebbe fatto dentro [`set_dynaconf_environment`](https://github.com/Tech-Workers-Coalition-Italia/mobilizon-reshare/blob/4291985b6d091a350f71c4c7dba947c04dd5c658/tests/conftest.py#L52) e andrebbe settata e cancellata come le altre due.
- mettere come valore `mobilizon_reshare/.secrets.toml` rischia di spaccare il packaging dei test (i.e. quado si fanno girare i test distribuiti da pypi il path relativo rischia di essere invalido). va fatta tutta la giostra che c'e' da linea 133 a 136 di `tests/conftest.py`.
- bisogna cancellare le linee 136 e 140 di `tests/conftest.py`

2022-01-08 00:23 UTC, fishinthecalculator commented
In qualche modo la PR di Simone ha risolto tutto mi pare.

PRIMA: https://github.com/Tech-Workers-Coalition-Italia/mobilizon-reshare/runs/4744554891?check_suite_focus=true
DOPO: https://github.com/Tech-Workers-Coalition-Italia/mobilizon-reshare/runs/4744987474?check_suite_focus=true

2022-01-08 09:39 UTC, chobeat commented
sì non l'avevo notato: mai mettere path hardcodati, usare sempre pkg_resources

2022-01-10 09:11 UTC, chobeat approved these changes

2022-02-16 10:28 UTC, closed without merging