publishers: Add Zulip publisher.
Tech-Workers-Coalition-Italia/mobilizon-reshare pull request #62
Opened 2021-09-14 21:23 UTC by fishinthecalculator

I added a `_send_private` function as well: it just sends a DM to a given user. You can test it id by sending a message to yourself via the web gui, noting down the integer in the URL (it'll be something like https://zulip.twc-italia.org/#narrow/pm-with/666-user666,  where 666 is your user id), and the simply paste it in the function.

2021-09-14 21:32 UTC, tinoilcotechino commented
should fix #57

2021-09-15 06:57 UTC, chobeat requested changes
Also add a couple tests mocking the zulip response

2021-09-15 06:57 UTC, chobeat commented on mobilizon_reshare/publishers/zulip.py
> +        # For private messages
I think this comment is not needed

2021-09-15 06:57 UTC, chobeat commented on mobilizon_reshare/publishers/zulip.py
> +        curl -X POST https://yourZulipDomain.zulipchat.com/api/v1/messages \
same

2021-09-15 06:57 UTC, chobeat commented on mobilizon_reshare/publishers/zulip.py
> +    def _preprocess_event(self):
I think this is not used here, it's a copypaste

2021-09-15 23:02 UTC, tinoilcotechino commented
whoops i forgot the test, ignore the reviewing request

2021-09-22 20:52 UTC, chobeat commented
is it done?

2021-09-25 21:30 UTC, tinoilcotechino commented
It's finished. I threw in some small changes to the release script

2021-09-26 09:37 UTC, chobeat requested changes

2021-09-26 09:37 UTC, chobeat commented on tests/publishers/conftest.py
> +api_uri = "https://zulip.twc-italia.org/api/v1/"
all this stuff is specific to zulip so it shouldn't be in the conftest for all the publishers, especially if it has generic names. Move it to test_zulip or create a folder for all the zulip stuff

2021-09-26 18:12 UTC, merged